Task APIS
uwblueprint/marillac-place pull request #20
Opened 2023-11-02 01:21 UTC by shelleychen318

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-11-16 04:43 UTC, williamtran10 reviewed
I fixed most of your bugs dealing with the typing. You should take some time to understand all of the changes I made in the most recent commit. You still have bugs with gql but I'll leave those to you to solve. Also, there's a lot of repeated code here, especially before I fixed your bugs. Try to refactor your code rather than directly copy-and-pasting.

2023-11-26 16:07 UTC, williamtran10 commented
@shelleychen318 @jeessh run and fix lint please

2023-11-26 16:41 UTC, williamtran10 commented on package.json
> +{
You can delete `package-lock.json` `package.json` and `yarn.lock` in the root folder since we don't install any modules at the root. We only install modules in `backend/typescript` or `frontend` folders.

2023-11-26 20:16 UTC, jeessh commented on package.json
> +{
deleted and committed lint fixes

2023-11-27 04:01 UTC, benymng commented on backend/typescript/prisma/schema.prisma
> +	//@@map("RecurrenceFrequency")
Remove comment

2023-11-27 04:14 UTC, benymng requested changes
Looks good for the most part but just a few comments to check. I tried running it locally but I was getting the error below. I am not sure if it's a local issue for me though so maybe try checking to see if it works locally for you too. 

<img width="1067" alt="image" src="https://github.com/uwblueprint/marillac-place/assets/60500272/d1f5c2a2-b438-4198-b089-2378fec81679">

2023-11-27 04:14 UTC, benymng commented on backend/typescript/services/implementations/taskService.ts
> +    assignee == null ? undefined : `${assignee.firstName} ${assignee.lastName}`;
Is the intended behaviour to let the assignee_name be undefined if the taskExtended doesn't have an assignee?

2023-11-27 04:14 UTC, benymng commented on backend/typescript/services/implementations/taskService.ts
> +  | null
Why is there a "|" in front of null? Shouldn't this be specifying that the type of TaskExtended is either null or with the category, assignee, and assigner?

2023-11-27 04:14 UTC, benymng commented on backend/typescript/services/implementations/taskService.ts
> +  async createTask(cTask: InputTaskDTO): Promise<TaskDTO> {
what is the though process behind cTask as the argument name? A little bit unintuitive

2023-11-27 04:14 UTC, benymng commented on backend/typescript/services/implementations/taskService.ts
> +      const taskDel = await prisma.task.delete({
maybe rename this to deletedTask to make it more clear what you are returning

2023-11-29 05:54 UTC, jeessh commented on backend/typescript/services/implementations/taskService.ts
> +    assignee == null ? undefined : `${assignee.firstName} ${assignee.lastName}`;
I believe so

2023-11-29 05:57 UTC, jeessh commented on backend/typescript/services/implementations/taskService.ts
> +    assignee == null ? undefined : `${assignee.firstName} ${assignee.lastName}`;
Also responding to the local error, I've ran into that before and works for my local end. If I recall it was something to do with the database in backend .env

2023-11-29 06:03 UTC, jeessh commented on backend/typescript/services/implementations/taskService.ts
> +  | null
Apparently it was just something to make it prettier 
<img width="656" alt="image" src="https://github.com/uwblueprint/marillac-place/assets/87463074/7add8f9e-aa79-40f4-828b-ebb883582293">

2023-11-29 06:03 UTC, jeessh commented on backend/typescript/services/implementations/taskService.ts
> +  async createTask(cTask: InputTaskDTO): Promise<TaskDTO> {
changed to inputTask

2023-11-29 06:03 UTC, jeessh commented on backend/typescript/services/implementations/taskService.ts
> +      const taskDel = await prisma.task.delete({
changed!

2023-11-30 02:12 UTC, selena1108 commented on backend/typescript/graphql/types/taskType.ts
> +    category: String!
Note for future: consider making category/assigner/assignee to return the entire object instead of individual fields

2023-11-30 02:15 UTC, selena1108 commented on backend/typescript/services/interfaces/taskService.ts
> +  category_name?: string;
This doesn't match the one in taskType.ts (category). Also not camel case

2023-11-30 02:15 UTC, selena1108 commented on backend/typescript/services/interfaces/taskService.ts
> +  category_name?: string;
Also lines 25-26 with assignee/assigner names

2023-11-30 03:22 UTC, selena1108 commented on backend/typescript/services/implementations/taskService.ts
> +class TaskService implements ITaskService {
I tested all the API's and only delete is actually working. createTask worked when Nandini and I fixed it but now it needs fixing again. TODO: fix all APIs (Saturday?)

2023-11-30 03:25 UTC, selena1108 commented on backend/typescript/graphql/types/taskType.ts
> +    startDate: DateTime!
I'm not sure if it makes sense for startDate to be nullable/endDate to be mandatory

2023-11-30 03:27 UTC, selena1108 commented on backend/typescript/graphql/types/taskType.ts
> +    assignerId: Int!
I think assigner should definitely not be nullable (it's just whoever is making the task). Reconsider/get input regarding assignee (if a staff wants to make a task then assign it later?) 
Same in TaskDTO

2023-11-30 03:29 UTC, selena1108 commented on backend/typescript/graphql/types/taskType.ts
> +import { gql } from "apollo-server-express";
TODO: make sure the types on this file (taskType.ts), interfaces, and schema.prisma all match with spelling/casing/types etc

2023-12-07 03:03 UTC, selena1108 commented
Note for future: consider making category/assigner/assignee to return the entire object instead of individual fields in backend/typescript/graphql/types/taskType.ts

2023-12-07 16:55 UTC, williamtran10 approved these changes
Lgtm, squash and merge when you're ready.

2023-12-09 16:14 UTC, merged