added endpoints for staff
uwblueprint/marillac-place pull request #26
Opened 2023-11-23 02:29 UTC by benymng

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Admin-API-Backend-Simple-functionality-2becf724f4724de28fddf4bc8b4a3e6c?pvs=4)

## Implementation description
* Created new endpoints for the staff (get all staff, get staff by ID, update, delete, create new staff)

## What should reviewers focus on?
* Need to check the naming convention for the prisma

2023-11-25 16:35 UTC, williamtran10 reviewed
Issues should be resolved now, just needed to merge dev into this branch to get a TypeScript update. Can you double-check that this works by testing it on your side?

2023-11-27 22:12 UTC, NandiniMeh commented on backend/typescript/graphql/types/staffType.ts
> +    roleId: Float!
Are role IDs expected to be a Float? If a decimal place in roleID isn't expected maybe this should be changed to Int/String (if they're UUIDs)

2023-11-27 22:15 UTC, NandiniMeh commented on backend/typescript/services/implementations/staffService.ts
> +      Logger.error(`Failed to update staff #${id} because ${getErrorMessage(error)}`);
Would need to change the error message here to `Failed to delete staff` rather than `Failed to update staff`

2023-11-27 22:24 UTC, NandiniMeh requested changes
In the DTOs, unless it is specifically required for roleId to be a Float, change to Int

2023-12-02 17:09 UTC, williamtran10 approved these changes
LGTM

2023-12-02 18:11 UTC, merged