feat: create task data models
uwblueprint/marillac-place pull request #6
Opened 2023-10-14 16:10 UTC by shelleychen318

## Notion ticket link

[Ticket Name][(https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)](https://www.notion.so/uwblueprintexecs/F23-Task-Board-181d7a3269374b4c95cca79e331b87e1?p=dd85e80868464d3483335cb7520db7ed&pm=s)

## Implementation description
* Added task data models

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-10-15 00:03 UTC, williamtran10 requested changes
Good work, I added some comments and some questions.
You can also checkout the link I sent in the slack about auto-formatting `schema.prisma`.

2023-10-15 00:03 UTC, williamtran10 commented on backend/typescript/prisma/schema.prisma
> +enum Categories {
Should we turn `categories` into its own model so that it can dynamically change?

2023-10-15 00:03 UTC, williamtran10 commented on backend/typescript/prisma/schema.prisma
> +    date_issued DateTime
Should this default to `now()`

2023-10-15 00:03 UTC, williamtran10 commented on backend/typescript/prisma/schema.prisma
> +enum Categories {
(This would also make `categories` and `tasks` a one-to-many relation)

2023-10-15 00:03 UTC, williamtran10 commented on backend/typescript/prisma/schema.prisma
> +    recurrence_frequency String?
Should this be an enum?

2023-10-15 00:03 UTC, williamtran10 commented on backend/typescript/prisma/schema.prisma
> +    // recurrence_days String // store days a comma separted string to be parsed for usage
This line is safe to remove now

2023-10-15 00:03 UTC, williamtran10 commented on backend/typescript/prisma/schema.prisma
> +    resident_id Int @id @default(autoincrement())
Warnings should have their own `id` that is set as `@id`.
The field that is set as `@id` must be unique so having it this way means that each resident can only have up to 1 warning which isn't true.
Instead set up a different `id` field as `@id`, then `resident_id` will need to be setup as a relation similar to `related_task` at the bottom of this file.

2023-10-19 01:04 UTC, shelleychen318 commented
Please see Selena and Nandini's PR for my changes: https://github.com/uwblueprint/marillac-place/pull/7

2023-10-19 20:45 UTC, closed without merging